/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.tapjoy;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollInvocation;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

@Kroll.module(name="Tapjoy", id="com.tapjoy")
public class TapjoyModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TapjoyModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TapjoyModule(TiContext tiContext) {
		super(tiContext);
	}

	// Methods
	@Kroll.method
	public void connectCreate(KrollInvocation invocation) {
		TapjoyConnect.getTapjoyConnectInstance(invocation.getTiContext().getActivity().getApplicationContext());
	}

	@Kroll.method
	public void connectDestroy(KrollInvocation invocation) {
		TapjoyConnect.getTapjoyConnectInstance(invocation.getTiContext().getActivity().getApplicationContext()).finalize();
	}
	
}
